<?php
  include("admin/auth.php");
  include("layout/sidebar.php");
  include("layout/header.php");
?>
<?php
  include("bagansungai.php"); 
?>
<br/><br/>
<?php
  include("chart/chart.php")
?>
<?php
  include("layout/footer.php");
?>		